name: Upload coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: Token used to upload coverage reports to Codecov
        required: true

jobs:
  upload:
    name: Upload report to Codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download coverage report
        uses: actions/download-artifact@v8
        with:
          name: coverage-report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unit-tests
          name: bcch-sdk
          disable_search: true
          fail_ci_if_error: true
